server:
  port: 1212

spring:
  application:
    name: Expense-Tracker

  datasource:
    url: jdbc:mysql://localhost:3306/harikumar
    username: root
    password: system

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp